version: '3'
services:
  dotnet_sdk:
    image: mcr.microsoft.com/dotnet/sdk:7.0
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    networks:
      - taskTracker
    volumes:
      - ./src:/app
      - ./.env:/env/.env
    command: "tail -f /dev/null" 
    working_dir: /app
  
networks:
  taskTracker:
    ipam:
      driver: default