version: '3'

services:
  dotnet_sdk:
    build:
      context: ./docker/dotnet-sdk
      dockerfile: dockerfile
    ports:
      - "${PORT:-5000}:${PORT:-5000}"
    volumes:
      - ./src:/app
    command: "dotnet run watch"
    working_dir: /app
    env_file:
      - .env
    depends_on:
      - mssql

  mssql:
    image: mcr.microsoft.com/mssql/server:2022-CU12-ubuntu-22.04
    ports:
      - '${DB_PORT:-1433}:1433'
    environment:
      SA_PASSWORD: '${DB_PASSWORD}'
      MSSQL_DB: '${DB_DATABASE}'
      ACCEPT_EULA: 'Y'
    volumes:
      - 'mssql-data:/var/opt/mssql'

volumes:
  mssql-data: